language: node_js
node_js:
 - "node"

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

script:
- npx cypress run --record --parallel
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
